name: GitHub activity in README

on:
  schedule:
    - cron: '0 */6 * * *'   # every 6 hours is plenty
  workflow_dispatch:

permissions:
  contents: write           # needed to update README.md

jobs:
  update-readme:
    name: Update activity section in README
    runs-on: ubuntu-latest
    concurrency:
      group: github-activity
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update recent activity
        uses: jamesgeorge007/github-activity-readme@v0.4.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          MAX_LINES: 10
